name: file_previewer
description: Generate a thumbnail for a file based on the file extension. Uses the native files previewer on iOS.
version: 0.1.0
repository: https://github.com/DutchCodingCompany/file_preview

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  pdfx: ^2.6.0
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dcc.file_previewer
        pluginClass: FilePreviewerPlugin
      ios:
        pluginClass: FilePreviewerPlugin
